# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('Inicio', models.DateTimeField(blank=True, null=True)),
                ('Fin', models.DateTimeField(blank=True, null=True)),
                ('diaEntero', models.NullBooleanField()),
                ('asigna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_asignacion_created', to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_visita_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
