# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_auto_20161110_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaluo',
            name='avaluo_id',
        ),
        migrations.AddField(
            model_name='avaluo',
            name='Estatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avaluo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
