# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_avaluo_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluo',
            name='Salida',
            field=models.DateField(null=True),
        ),
    ]
