# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_auto_20161110_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluo',
            name='Solicitud',
            field=models.DateField(null=True),
        ),
    ]
